## In Machine Learning, OVR stands for One-vs-Rest (or One-vs-All).

It is a strategy used for multi-class classification where a model is trained like this:

## Email Spam Classification

Suppose you want to classify emails into 3 classes:

1.Spam
2.Promotions
3.Important

**How OVR works:**

**You train 3 models:**

`Model 1:` Spam vs (Promotions + Important)

`Model 2:` Promotions vs (Spam + Important)

`Model 3:` Important vs (Spam + Promotions)

When a new email comes:

All 3 models give a score:

Spam model → 0.2
Promotions model → 0.6
Important model → 0.3

Highest score = Promotions (0.6)

So final prediction = Promotions

### Simple summary:

OVR means each class gets its own “yes/no detector”, and the strongest detector decides the final class.

In [1]:
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

df = pd.read_csv("ovr_real_world_categorical.csv")  # ya dataset file
df.head()

   age  gender      city     education  income  target_class
0   56  Female  Peshawar     Bachelors  139879             2
1   38    Male    Lahore     Bachelors  188266             2
2   28  Female  Peshawar       Masters   36023             0
3   20  Female  Peshawar  Intermediate   79735             1
4   47  Female    Lahore       Masters  123355             2

In [2]:
df.isnull().sum()

age             0
gender          0
city            0
education       0
income          0
target_class    0
dtype: int64

In [3]:
df.duplicated().sum()

np.int64(0)

In [4]:
df.dtypes

age              int64
gender          object
city            object
education       object
income           int64
target_class     int64
dtype: object

In [5]:
df['gender'].unique()

array(['Female', 'Male'], dtype=object)

In [6]:
df['city'].unique()

array(['Peshawar', 'Lahore', 'Quetta', 'Islamabad', 'Karachi'],
      dtype=object)

In [7]:
df['education'].unique()

array(['Bachelors', 'Masters', 'Intermediate', 'Matric'], dtype=object)

In [8]:
df.head()

   age  gender      city     education  income  target_class
0   56  Female  Peshawar     Bachelors  139879             2
1   38    Male    Lahore     Bachelors  188266             2
2   28  Female  Peshawar       Masters   36023             0
3   20  Female  Peshawar  Intermediate   79735             1
4   47  Female    Lahore       Masters  123355             2

In [9]:
from sklearn.preprocessing import LabelEncoder

for col in ["gender", "city", "education"]:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col])

In [10]:
df.head()

   age  gender  city  education  income  target_class
0   56       0     3          0  139879             2
1   38       1     2          0  188266             2
2   28       0     3          2   36023             0
3   20       0     3          1   79735             1
4   47       0     2          2  123355             2

In [11]:
df['city'].unique()

array([3, 2, 4, 0, 1])

In [12]:
df['education'].unique()

array([0, 2, 1, 3])

In [14]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
df[["age", "income"]] = scaler.fit_transform(df[["age", "income"]])

In [15]:
df.head()

        age  gender  city  education    income  target_class
0  1.428174       0     3          0  0.519115             2
1 -0.061145       1     2          0  1.447404             2
2 -0.888544       0     3          2 -1.473328             0
3 -1.550464       0     3          1 -0.634728             1
4  0.683515       0     2          2  0.202108             2

In [16]:
from sklearn.model_selection import train_test_split

X = df.drop("target_class", axis=1)
y = df["target_class"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [17]:
from sklearn.multiclass import OneVsRestClassifier
from sklearn.linear_model import LogisticRegression

model = OneVsRestClassifier(LogisticRegression(max_iter=1000))
model.fit(X_train, y_train)

OneVsRestClassifier(estimator=LogisticRegression(max_iter=1000))

In [18]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

y_pred = model.predict(X_test)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.91      1.00      0.95        40
           1       1.00      0.83      0.91        72
           2       0.92      1.00      0.96        88

    accuracy                           0.94       200
   macro avg       0.94      0.94      0.94       200
weighted avg       0.95      0.94      0.94       200